[project]
name = "foundry-base"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "eth-account>=0.13.4",
    "web3>=7.6.0",
]
